### ISSUE TITLE
Game Vote

### ISSUE THREAD

**Issue by Ezbob** [DanThrane/phaser-game-off#1]
We now have two proposals (see the proposal folder for details); and the time has come for us to vote on the proposal that we want to work on. The candidates are:

1. Actraiser clone
2. MyChimera
3. RotMG

To make a vote, please respond with  either the name of the candiate you support or the number of the candidate as shown above.

Dealine for voting is 8th of November 18:00.

**Comment by DanThrane** [comment]
2

**Comment by SneManden** [comment]
Naturligvis vil jeg stemme på mit eget forslag. Såfremt vi anvender en "du må ikke stemme på din egen"-politik, tror jeg at jeg går med Dan på **2**.

**Comment by Ezbob** [comment]
Jeg synes helst man ikke skal stemme på ens egen foreslag, så jeg stemmer på 1. Selvom jeg synes 3 lyder interessant.

**Comment by Tiggles** [comment]
Jeg bryder med strømmen og stemmer *3*. Hvis David ikke når at stemme inden i morgen, så vinder 2. Ellers kan han vel forårsage tie mellem 1 og 2 eller 2 og 3, afhængigt af hvad han stemmer.

**Comment by D4vidH4mm3r** [comment]
Jeg vil stemme i stil med ranked-choice voting og sige:

1. Option 3 (RotMG)
2. Option 1
3. Option 2

**Comment by Ezbob** [comment]
Det ser ud til at vi har en tie mellem mulighed 3(David, Jonas) og 2(Dan, Casper) med mindre der er nogen der vil skifte mening (_looking at @SneManden_)?

**Comment by SneManden** [comment]
Trap card activated! Min dynamic vote træder i kraft: stemmen går til 1.
Der er tale om en rekursiv funktion uden stop, så min stemme går igen til 2.
Dermed pr. Matematik er min stemme både på 1 og på 2 _eller_ hverken på 1 eller 2. Dvs 3 vinder?

**Comment by Tiggles** [comment]
Huzzah! Skal vi oprette issues på forskellige dele af spillet som folk kan hægte sig på?

**Comment by DanThrane** [comment]
Bare for at der ikke er nogen tvetydighed, så flytter jeg min stemme til 3. Så kan vi godt lukke den her issue.
