### ISSUE TITLE
Tiles only show in a small square (16x16 tiles) instead of full room definition

### ISSUE THREAD

**Issue by SneManden** [DanThrane/phaser-game-off#2]
See screenshot:
![image](https://user-images.githubusercontent.com/1940764/48291408-a2004280-e476-11e8-8d0a-8ab1dd2b4f06.png)

**Comment by DanThrane** [comment]
I did a quick test with Tiled instead, that appears to have fixed the issue. Not sure how room generation would work with Tiled. Maybe a layer per room type?

Regardless I have put the code in the tiled branch.
